language: python
arch:
  - amd64
python:
  - 3.6
  - 3.7
jobs:
  include:
    #  ====== WINDOWS =========
    - name: "Python 3.6.8 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.6.8
        - python -m pip install scikit-build
        - python -m pip install pytest pylint
      install:
        - python --version
        - python -m pip install .
      script:
        - pylint mlchain
        - pytest tests/
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - name: "Python 3.7.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.4
        - python -m pip install scikit-build
        - python -m pip install pytest pylint
      install:
        - python --version
        - python -m pip install .
      script:
        - pylint mlchain
        - pytest tests/
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

before_install:
  - sudo apt-get update
  - sudo apt-get install -y software-properties-common
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends build-essential gcc
  - pip install scikit-build
  - pip install pytest pylint
install:
  - python --version
  - pip install .
script:
  - pylint mlchain
  - pytest tests/